In [ ]:
import pandas as pd

In [ ]:
df_train = pd.read_csv('train.csv')

In [ ]:
df_train.describe()

ID          Age  Work_Experience  Family_Size
count    8068.000000  8068.000000      7239.000000  7733.000000
mean   463479.214551    43.466906         2.641663     2.850123
std      2595.381232    16.711696         3.406763     1.531413
min    458982.000000    18.000000         0.000000     1.000000
25%    461240.750000    30.000000         0.000000     2.000000
50%    463472.500000    40.000000         1.000000     3.000000
75%    465744.250000    53.000000         4.000000     4.000000
max    467974.000000    89.000000        14.000000     9.000000

In [ ]:
df_train.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Var_1',
       'Segmentation'],
      dtype='object')

In [ ]:
df_train['Segmentation'].unique()

array(['D', 'A', 'B', 'C'], dtype=object)

In [ ]:
df_train['Var_1'].unique()

array(['Cat_4', 'Cat_6', 'Cat_7', 'Cat_3', 'Cat_1', 'Cat_2', nan, 'Cat_5'],
      dtype=object)

In [ ]:
df_train.drop(['Var_1'],axis = 1, inplace = True)

In [ ]:
df_train.head()

ID  Gender Ever_Married  Age Graduated     Profession  Work_Experience  \
0  462809    Male           No   22        No     Healthcare              1.0   
1  462643  Female          Yes   38       Yes       Engineer              NaN   
2  466315  Female          Yes   67       Yes       Engineer              1.0   
3  461735    Male          Yes   67       Yes         Lawyer              0.0   
4  462669  Female          Yes   40       Yes  Entertainment              NaN   

  Spending_Score  Family_Size Segmentation  
0            Low          4.0            D  
1        Average          3.0            A  
2            Low          1.0            B  
3           High          2.0            B  
4           High          6.0            A

Feature Engineering

In [ ]:
df_train['Gender'].replace(['Female','Male'],[0,1],inplace = True)

<ipython-input-26-1928e834d2a1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Gender'].replace(['Female','Male'],[0,1],inplace = True)
<ipython-input-26-1928e834d2a1>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['Gender'].replace(['Female','Male'],[0,1],inplace = True)


In [ ]:
df_train['Ever_Married'].replace(['No','Yes'],[0,1],inplace = True)

<ipython-input-27-0c38efdfe368>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Ever_Married'].replace(['No','Yes'],[0,1],inplace = True)
<ipython-input-27-0c38efdfe368>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['Ever_Married'].replace(['No','Yes'],[0,1],inplace = True)


In [ ]:
df_train['Graduated'].replace(['No','Yes'],[0,1],inplace=True)

<ipython-input-28-abd97134003c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Graduated'].replace(['No','Yes'],[0,1],inplace=True)
<ipython-input-28-abd97134003c>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['Graduated'].replace(['No','Yes'],[0,1],inplace=True)


In [ ]:
df_train = pd.get_dummies(df_train, columns=['Profession'])

In [ ]:
df_train = df_train.fillna(0)

In [ ]:
df_train = pd.get_dummies(df_train, columns=['Spending_Score'])

In [ ]:
for col in df_train.columns:
  try:
    df_train[col] = df_train[col].astype(int)
  except:
    pass

In [ ]:
df_train.head()

ID  Gender  Ever_Married  Age  Graduated  Work_Experience  Family_Size  \
0  462809       1             0   22          0                1            4   
1  462643       0             1   38          1                0            3   
2  466315       0             1   67          1                1            1   
3  461735       1             1   67          1                0            2   
4  462669       0             1   40          1                0            6   

  Segmentation  Profession_Artist  Profession_Doctor  Profession_Engineer  \
0            D                  0                  0                    0   
1            A                  0                  0                    1   
2            B                  0                  0                    1   
3            B                  0                  0                    0   
4            A                  0                  0                    0   

   Profession_Entertainment  Profession_Executive  Profession_Healthcare  \
0                         0                     0                      1   
1                         0                     0                      0   
2                         0                     0                      0   
3                         0                     0                      0   
4                         1                     0                      0   

   Profession_Homemaker  Profession_Lawyer  Profession_Marketing  \
0                     0                  0                     0   
1                     0                  0                     0   
2                     0                  0                     0   
3                     0                  1                     0   
4                     0                  0                     0   

   Spending_Score_Average  Spending_Score_High  Spending_Score_Low  
0                       0                    0                   1  
1                       1                    0                   0  
2                       0                    0                   1  
3                       0                    1                   0  
4                       0                    1                   0

Building Models

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression(multi_class='ovr', solver='liblinear')

In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr', solver='liblinear')

In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr', solver='liblinear')

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
import numpy as np
print(np.unique(y_train, return_counts=True))

(array([0, 1, 2, 3]), array([1581, 1489, 1590, 1794]))


In [ ]:
np.unique(y_pred)

array([3])

In [ ]:
y_test

array([3, 0, 3, ..., 0, 0, 3])

In [ ]:
le = LabelEncoder()
df_train['Segmentation_encoded'] = le.fit_transform(df_train['Segmentation'])

In [ ]:
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'A': np.int64(0), 'B': np.int64(1), 'C': np.int64(2), 'D': np.int64(3)}


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = df_train.drop(['Segmentation_encoded','ID','Segmentation'],axis=1)
y = df_train['Segmentation_encoded']



model = LogisticRegression(multi_class='ovr', solver='liblinear', max_iter=100)
model.fit(X, y)

# y_pred = model.predict(X_test)

# # Decode predictions
# y_pred_labels = le.inverse_transform(y_pred)

# # Check prediction distribution
# import numpy as np
# print("Predicted:", np.unique(y_pred_labels, return_counts=True))


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr', solver='liblinear')

In [ ]:
y_pred

array([0, 2, 3, ..., 1, 3, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

In [ ]:
accuracy

0.49318463444857497

In [ ]:
y_test

742     3
2127    0
2107    3
2943    2
4362    3
       ..
3196    0
6302    1
4377    0
3473    0
4776    3
Name: Segmentation_encoded, Length: 1614, dtype: int64

In [ ]:
y_pred

array([0, 2, 3, ..., 1, 3, 0])

In [ ]:
df_train.shape

(8068, 21)